/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request */
        post: operations["password_reset_request_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Complete */
        post: operations["password_reset_complete_auth_password_reset_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Workspace */
        patch: operations["rename_workspace_workspaces__workspace_id__patch"];
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["update_connection_connections__connection_id__patch"];
        trace?: never;
    };
    "/connections/{connection_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_connections__connection_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}/reload-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload Schema */
        post: operations["reload_schema_connections__connection_id__reload_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_connections__connection_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_llm_keys_get"];
        put?: never;
        /** Create Key */
        post: operations["create_key_llm_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Key */
        delete: operations["delete_key_llm_keys__key_id__delete"];
        options?: never;
        head?: never;
        /** Update Key */
        patch: operations["update_key_llm_keys__key_id__patch"];
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Query */
        post: operations["post_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Query Stream */
        post: operations["post_query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Query Export */
        post: operations["post_query_export_query_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_history__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Clear History
         * @description Reset the multi-turn Redis conversation buffer for this session.
         */
        delete: operations["clear_history_history__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_favorites_get"];
        put?: never;
        /** Save Favorite */
        post: operations["save_favorite_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{favorite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Favorite */
        delete: operations["delete_favorite_favorites__favorite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{request_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_query__request_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examples */
        get: operations["list_examples_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description Returned on register/login. Tokens travel in cookies, not the body.
         *
         *     ``csrf_token`` is returned so the SPA can echo it in the X-CSRF-Token header
         *     on state-changing requests.
         */
        AuthResponse: {
            user: components["schemas"]["UserOut"];
            workspace: components["schemas"]["WorkspaceOut"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /** Name */
            name: string;
            /**
             * Dialect
             * @default postgres
             * @enum {string}
             */
            dialect: "postgres" | "mysql";
            /** Host */
            host: string;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /** Database */
            database: string;
            /** Username */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
            /** Ssl Mode */
            ssl_mode?: string | null;
            /**
             * Read Only
             * @default true
             */
            read_only: boolean;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Dialect */
            dialect: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Database */
            database: string;
            /** Username */
            username: string;
            /** Ssl Mode */
            ssl_mode: string | null;
            /** Read Only */
            read_only: boolean;
            /** Index Status */
            index_status: string;
            /** Index Error */
            index_error: string | null;
            /** Last Introspected At */
            last_introspected_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConnectionTestResponse */
        ConnectionTestResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Server Version */
            server_version?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** ConnectionUpdate */
        ConnectionUpdate: {
            /** Name */
            name?: string | null;
            /** Host */
            host?: string | null;
            /** Port */
            port?: number | null;
            /** Database */
            database?: string | null;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Ssl Mode */
            ssl_mode?: string | null;
            /** Read Only */
            read_only?: boolean | null;
        };
        /** CorrectionStep */
        CorrectionStep: {
            /** Attempt */
            attempt: number;
            /** Failed Sql */
            failed_sql: string;
            /** Error */
            error: string;
        };
        /** ExampleCategory */
        ExampleCategory: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Queries */
            queries: components["schemas"]["ExampleQuery"][];
        };
        /** ExampleQuery */
        ExampleQuery: {
            /** Text */
            text: string;
            /** Icon */
            icon: string;
        };
        /** ExamplesResponse */
        ExamplesResponse: {
            /** Categories */
            categories: components["schemas"]["ExampleCategory"][];
        };
        /** FavoriteItem */
        FavoriteItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Question */
            question: string;
            /** Sql */
            sql: string;
            /** Tags */
            tags?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FavoritesResponse */
        FavoritesResponse: {
            /** Items */
            items: components["schemas"]["FavoriteItem"][];
            /** Total */
            total: number;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Session Id */
            session_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Rating */
            rating: string;
        };
        /** FkEdgeOut */
        FkEdgeOut: {
            /** From Table */
            from_table: string;
            /** From Column */
            from_column: string;
            /** To Table */
            to_table: string;
            /** To Column */
            to_column: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
            /** Llm Provider */
            llm_provider: string;
            /** Version */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HistoryItem */
        HistoryItem: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Request Id */
            request_id: string;
            /** Question */
            question: string;
            /** Final Sql */
            final_sql: string;
            /** Row Count */
            row_count: number;
            /** Retry Count */
            retry_count: number;
            /** Execution Time Ms */
            execution_time_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Session Id */
            session_id: string;
            /** Turns */
            turns: components["schemas"]["HistoryItem"][];
            /** Total */
            total: number;
        };
        /** IndexedColumnOut */
        IndexedColumnOut: {
            /** Name */
            name: string;
            /** Data Type */
            data_type: string;
            /** Is Nullable */
            is_nullable: boolean | null;
            /** Is Pk */
            is_pk: boolean | null;
            /** Is Fk */
            is_fk: boolean | null;
        };
        /** IndexedSchemaOut */
        IndexedSchemaOut: {
            /** Index Status */
            index_status: string;
            /** Table Count */
            table_count: number;
            /** Tables */
            tables: components["schemas"]["IndexedTableOut"][];
            /** Fks */
            fks: components["schemas"]["FkEdgeOut"][];
        };
        /** IndexedTableOut */
        IndexedTableOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Schema Name */
            schema_name: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Row Count */
            row_count: number | null;
            /** Description */
            description: string | null;
            /** Columns */
            columns: components["schemas"]["IndexedColumnOut"][];
        };
        /** LlmKeyCreate */
        LlmKeyCreate: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "anthropic" | "openai" | "gemini";
            /** Label */
            label?: string | null;
            /** Api Key */
            api_key: string;
            /** Model Override */
            model_override?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** LlmKeyOut */
        LlmKeyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Label */
            label: string | null;
            /** Model Override */
            model_override: string | null;
            /** Is Default */
            is_default: boolean;
            /** Key Hint */
            key_hint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LlmKeyUpdate */
        LlmKeyUpdate: {
            /** Label */
            label?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Model Override */
            model_override?: string | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserOut"];
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceOut"][];
        };
        /** PasswordResetComplete */
        PasswordResetComplete: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ProviderBreakdown */
        ProviderBreakdown: {
            /** Provider */
            provider: string;
            /** Query Count */
            query_count: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            /** Question */
            question: string;
            /** Llm Key Id */
            llm_key_id?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Sql */
            sql: string;
            /** Explanation */
            explanation: string;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Columns */
            columns: string[];
            /** Row Count */
            row_count: number;
            /** Execution Time Ms */
            execution_time_ms: number;
            visualization: components["schemas"]["VisualizationHint"];
            metadata: components["schemas"]["ResultMetadata"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ResultMetadata */
        ResultMetadata: {
            /** Retry Count */
            retry_count: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Llm Provider */
            llm_provider: string;
            /** Truncated */
            truncated: boolean;
            /** Request Id */
            request_id: string;
            /** Failed Stage */
            failed_stage?: string | null;
            /**
             * Corrections
             * @default []
             */
            corrections: components["schemas"]["CorrectionStep"][];
            retrieval?: components["schemas"]["RetrievalDisclosure"] | null;
        };
        /** RetrievalDisclosure */
        RetrievalDisclosure: {
            /** Tables */
            tables: components["schemas"]["RetrievedTableHint"][];
            /** Schema Tokens */
            schema_tokens: number;
        };
        /** RetrievedTableHint */
        RetrievedTableHint: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Via */
            via: string;
            /** Lexical */
            lexical: number;
            /** Vector */
            vector: number;
        };
        /** SaveFavoriteRequest */
        SaveFavoriteRequest: {
            /** Name */
            name: string;
            /** Question */
            question: string;
            /** Sql */
            sql: string;
            /** Tags */
            tags?: string | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Window Days */
            window_days: number;
            /** Query Count */
            query_count: number;
            /** Successful Query Count */
            successful_query_count: number;
            /** Failed Query Count */
            failed_query_count: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
            /** Avg Execution Time Ms */
            avg_execution_time_ms: number;
            /** Avg Retry Count */
            avg_retry_count: number;
            /** Feedback Up */
            feedback_up: number;
            /** Feedback Down */
            feedback_down: number;
            /** Providers */
            providers: components["schemas"]["ProviderBreakdown"][];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisualizationHint */
        VisualizationHint: {
            /**
             * Chart
             * @enum {string}
             */
            chart: "table" | "bar" | "line" | "pie" | "scatter" | "kpi";
            /** X */
            x?: string | null;
            /**
             * Y
             * @default []
             */
            y: string[];
            /** Label */
            label?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
                t2s_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_request_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_complete_auth_password_reset_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_workspace_workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_connections_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_connections__connection_id__test_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_schema_connections__connection_id__reload_schema_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_connections__connection_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexedSchemaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_llm_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmKeyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_llm_keys_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_llm_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_key_llm_keys__key_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmKeyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_query_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_export_query_export_post: {
        parameters: {
            query: {
                fmt: "csv" | "json";
            };
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_history__session_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_history__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_favorites_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_favorite_favorites_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_favorite_favorites__favorite_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                favorite_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_query__request_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: {
                t2s_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: {
                window_days?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_examples_examples_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
